parameters:
#    system.example.class: Livetech\SystemBundle\Example

services:
#    system.example:
#        class: %system.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
